services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: user_task
      POSTGRES_PASSWORD: user_task
      POSTGRES_DB: user_task
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: user-task
    restart: always
    depends_on:
      - db
    environment:
      # Django settings
      DJANGO_SETTINGS_MODULE: app.settings
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1

      # Database connection info
      DATABASE_URL: postgres://user_task:user_task@db/user_task

    ports:
      - "8000:8000"  

volumes:
  postgres_data:
