[project]
name = "user-task"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.8",
]

[dependency-groups]
dev = [
    "django-admin>=2.0.2",
]

[tool.black]
line-length = 120
skip-string-normalization = true